export const caracteristiquesTechniquesProduct = {
    'ordinateurs': [
        { property: 'numero_unique', title: 'Numéro unique' },
        { property: 'config', title: 'Config' },
        { property: 'marque', title: 'Marque' },
        { property: 'modele', title: 'Modèle' },
        { property: 'systeme_exploitation', title: 'Système d\'exploitation' },
        { property: 'processeur', title: 'Processeur' },
        { property: 'ram', title: 'RAM' },
        { property: 'stockage', title: 'Stockage' },
        { property: 'type_stockage', title: 'Type de stockage' },
        { property: 'taille_ecran', title: 'Taille écran' },
        { property: 'type_ecran', title: 'Type d\'écran' },
        { property: 'resolution_ecran', title: 'Résolution écran' },
        { property: 'temps_reponse_ecran', title: 'Temps de réponse écran' },
        { property: 'frequence_ecran', title: 'Fréquence écran' },
        { property: 'luminosite_ecran', title: 'Luminosité écran' },
        { property: 'carte_graphique', title: 'Carte graphique' },
        { property: 'audio', title: 'Audio' },
        { property: 'camera', title: 'Caméra' },
        { property: 'carac_camera', title: 'Caractéristiques de la caméra' },
        { property: 'connectivite', title: 'Connectivité' },
        { property: 'connectique', title: 'Connectique' },
        { property: 'alimentation', title: 'Alimentation' },
        { property: 'autonomie_batterie', title: 'Autonomie de la batterie' },
        { property: 'dimension', title: 'Dimension' },
        { property: 'poids', title: 'Poids' },
        { property: 'couleur', title: 'Couleur' },
        { property: 'clavier', title: 'Clavier' },
        { property: 'etat', title: 'Etat' },
        { property: 'norme_environement', title: 'Norme environnementale' },
        { property: 'empreinte_carbonne', title: 'Empreinte carbone' },
    ],
    'ecrans': [
        { property: 'numero_unique', title: 'Numéro unique' },
        { property: 'marque', title: 'Marque' },
        { property: 'modele', title: 'Modèle' },
        { property: 'taille_ecran', title: 'Taille écran' },
        { property: 'type_ecran', title: 'Type d\'écran' },
        { property: 'resolution_ecran', title: 'Résolution écran' },
        { property: 'frequence_ecran', title: 'Fréquence écran' },
        { property: 'luminosite_ecran', title: 'Luminosité écran' },
        { property: 'temps_reponse_ecran', title: 'Temps de réponse écran' },
        { property: 'connectivite', title: 'Connectivité' },
        { property: 'connectique', title: 'Connectique' },
        { property: 'alimentation', title: 'Alimentation' },
        { property: 'audio', title: 'Audio' },
        { property: 'camera', title: 'Caméra' },
        { property: 'carac_camera', title: 'Caractéristiques de la caméra' },
        { property: 'dimension', title: 'Dimension' },
        { property: 'poids', title: 'Poids' },
        { property: 'couleur', title: 'Couleur' },
        { property: 'etat', title: 'Etat' },
        { property: 'norme_environement', title: 'Norme environnementale' },
        { property: 'empreinte_carbonne', title: 'Empreinte carbone' }
    ],
    'telephones': [
        { property: 'numero_unique', title: 'Numéro unique' },
        { property: 'marque', title: 'Marque' },
        { property: 'modele', title: 'Modèle' },
        { property: 'config', title: 'Config' },
        { property: 'IMEI1', title: 'IMEI 1' },
        { property: 'IMEI2', title: 'IMEI 2' },
        { property: 'systeme_exploitation', title: 'Système d\'exploitation' },
        { property: 'processeur', title: 'Processeur' },
        { property: 'ram', title: 'RAM' },
        { property: 'stockage', title: 'Stockage' },
        { property: 'type_stockage', title: 'Type de stockage' },
        { property: 'taille_ecran', title: 'Taille écran' },
        { property: 'type_ecran', title: 'Type d\'écran' },
        { property: 'resolution_ecran', title: 'Résolution écran' },
        { property: 'frequence_ecran', title: 'Fréquence écran' },
        { property: 'luminosite_ecran', title: 'Luminosité écran' },
        { property: 'carte_graphique', title: 'Carte graphique' },
        { property: 'camera', title: 'Caméra' },
        { property: 'carac_camera', title: 'Caractéristiques de la caméra' },
        { property: 'connectivite', title: 'Connectivité' },
        { property: 'connectique', title: 'Connectique' },
        { property: 'alimentation', title: 'Alimentation' },
        { property: 'audio', title: 'Audio' },
        { property: 'autonomie_batterie', title: 'Autonomie de la batterie' },
        { property: 'dimension', title: 'Dimension' },
        { property: 'poids', title: 'Poids' },
        { property: 'couleur', title: 'Couleur' },
        { property: 'etat', title: 'Etat' },
        { property: 'garantie', title: 'Garantie' },
        { property: 'norme_environement', title: 'Norme environnementale' },
        { property: 'empreinte_carbonne', title: 'Empreinte carbone' },
    ],
    'tablettes': [
        { property: 'numero_unique', title: 'Numéro unique' },
        { property: 'marque', title: 'Marque' },
        { property: 'modele', title: 'Modèle' },
        { property: 'config', title: 'Config' },
        { property: 'IMEI1', title: 'IMEI 1' },
        { property: 'IMEI2', title: 'IMEI 2' },
        { property: 'systeme_exploitation', title: 'Système d\'exploitation' },
        { property: 'processeur', title: 'Processeur' },
        { property: 'ram', title: 'RAM' },
        { property: 'stockage', title: 'Stockage' },
        { property: 'type_stockage', title: 'Type de stockage' },
        { property: 'taille_ecran', title: 'Taille écran' },
        { property: 'type_ecran', title: 'Type d\'écran' },
        { property: 'resolution_ecran', title: 'Résolution écran' },
        { property: 'frequence_ecran', title: 'Fréquence écran' },
        { property: 'luminosite_ecran', title: 'Luminosité écran' },
        { property: 'carte_graphique', title: 'Carte graphique' },
        { property: 'camera', title: 'Caméra' },
        { property: 'carac_camera', title: 'Caractéristiques de la caméra' },
        { property: 'connectivite', title: 'Connectivité' },
        { property: 'connectique', title: 'Connectique' },
        { property: 'alimentation', title: 'Alimentation' },
        { property: 'audio', title: 'Audio' },
        { property: 'autonomie_batterie', title: 'Autonomie de la batterie' },
        { property: 'dimension', title: 'Dimension' },
        { property: 'poids', title: 'Poids' },
        { property: 'couleur', title: 'Couleur' },
        { property: 'etat', title: 'Etat' },
        { property: 'garantie', title: 'Garantie' },
        { property: 'norme_environement', title: 'Norme environnementale' },
        { property: 'empreinte_carbonne', title: 'Empreinte carbone' },
    ],
    'casques-micros': [
        { property: 'numero_unique', title: 'Numéro unique' },
        { property: 'marque', title: 'Marque' },
        { property: 'modele', title: 'Modèle' },
        { property: 'audio', title: 'Audio' },
        { property: 'connectivite', title: 'Connectivité' },
        { property: 'connectique', title: 'Connectique' },
        { property: 'dimension', title: 'Dimension' },
        { property: 'poids', title: 'Poids' },
        { property: 'couleur', title: 'Couleur' },
        { property: 'etat', title: 'Etat' },
        { property: 'garantie', title: 'Garantie' },
        { property: 'norme_environement', title: 'Norme environnementale' },
        { property: 'empreinte_carbonne', title: 'Empreinte carbone' },
    ],
    'claviers': [
        { property: 'numero_unique', title: 'Numéro unique' },
        { property: 'marque', title: 'Marque' },
        { property: 'modele', title: 'Modèle' },
        { property: 'autonomie_batterie', title: 'Autonomie de la batterie' },
        { property: 'connectivite', title: 'Connectivité' },
        { property: 'connectique', title: 'Connectique' },
        { property: 'clavier', title: 'Clavier' },
        { property: 'dimension', title: 'Dimension' },
        { property: 'poids', title: 'Poids' },
        { property: 'couleur', title: 'Couleur' },
        { property: 'etat', title: 'Etat' },
        { property: 'garantie', title: 'Garantie' },
        { property: 'norme_environement', title: 'Norme environnementale' },
        { property: 'empreinte_carbonne', title: 'Empreinte carbone' },
    ],
    'souris': [
        { property: 'numero_unique', title: 'Numéro unique' },
        { property: 'marque', title: 'Marque' },
        { property: 'modele', title: 'Modèle' },
        { property: 'autonomie_batterie', title: 'Autonomie de la batterie' },
        { property: 'connectivite', title: 'Connectivité' },
        { property: 'connectique', title: 'Connectique' },
        { property: 'dimension', title: 'Dimension' },
        { property: 'poids', title: 'Poids' },
        { property: 'couleur', title: 'Couleur' },
        { property: 'etat', title: 'Etat' },
        { property: 'garantie', title: 'Garantie' },
        { property: 'norme_environement', title: 'Norme environnementale' },
        { property: 'empreinte_carbonne', title: 'Empreinte carbone' },
    ],
    "adaptateurs": [
        { property: 'numero_unique', title: 'Numéro unique' },
        { property: 'marque', title: 'Marque' },
        { property: 'modele', title: 'Modèle' },
        { property: 'connectique', title: 'Connectique' },
        { property: 'alimentation', title: 'Alimentation' },
        { property: 'dimension', title: 'Dimension' },
        { property: 'poids', title: 'Poids' },
        { property: 'couleur', title: 'Couleur' },
        { property: 'etat', title: 'Etat' },
        { property: 'garantie', title: 'Garantie' },
        { property: 'norme_environement', title: 'Norme environnementale' },
        { property: 'empreinte_carbonne', title: 'Empreinte carbone' },
    ],
    "imprimantes": [
        { property: 'numero_unique', title: 'Numéro unique' },
        { property: 'type', title: 'Type' },
        { property: 'marque', title: 'Marque' },
        { property: 'modele', title: 'Modèle' },
        { property: 'connectivite', title: 'Connectivité' },
        { property: 'connectique', title: 'Connectique' },
        { property: 'dimension', title: 'Dimension' },
        { property: 'poids', title: 'Poids' },
        { property: 'couleur', title: 'Couleur' },
        { property: 'etat', title: 'Etat' },
        { property: 'garantie', title: 'Garantie' },
        { property: 'norme_environement', title: 'Norme environnementale' },
        { property: 'empreinte_carbonne', title: 'Empreinte carbone' },
    ],
    "licences": [
        { property: 'nom_produit', title: 'Nom du produit' },
        { property: 'fournisseur', title: 'Fournisseur' },
        { property: 'type_licence', title: 'Type de licence' },
    ],
    "cables": [
        { property: 'numero_unique', title: 'Numéro unique' },
        { property: 'marque', title: 'Marque' },
        { property: 'dimension', title: 'Dimension' },
        { property: 'etat', title: 'Etat' },
        { property: 'garantie', title: 'Garantie' },
        { property: 'norme_environement', title: 'Norme environnementale' },
        { property: 'empreinte_carbonne', title: 'Empreinte carbone' },
    ],
    "Autres": [
        { property: 'numero_unique', title: 'Numéro unique' },
        { property: 'marque', title: 'Marque' },
        { property: 'modele', title: 'Modèle' },
        { property: 'dimension', title: 'Dimension' },
        { property: 'poids', title: 'Poids' },
        { property: 'etat', title: 'Etat' },
        { property: 'garantie', title: 'Garantie' },
        { property: 'norme_environement', title: 'Norme environnementale' },
        { property: 'empreinte_carbonne', title: 'Empreinte carbone' },
    ]
};

export const mainCaracteristiquesTechniquesProduct = {
    'ordinateurs': [
        { property: 'ram', title: 'RAM' },
        { property: 'stockage', title: 'Stockage' },
        { property: 'type_stockage', title: 'Type de stockage' },
        { property: 'processeur', title: 'Processeur' },
        { property: 'taille_ecran', title: 'Taille écran' },
        { property: 'clavier', title: 'Clavier' },
        { property: 'etat', title: 'Etat' }
    ],
    'ecrans': [
        { property: 'taille_ecran', title: 'Taille écran' },
        { property: 'type_ecran', title: 'Type d\'écran' },
        { property: 'resolution_ecran', title: 'Résolution écran' },
        { property: 'frequence_ecran', title: 'Fréquence écran' },
        { property: 'temps_reponse_ecran', title: 'Temps de réponse écran' },
        { property: 'luminosité', title: 'Luminosité' },
        { property: 'etat', title: 'Etat' }
    ],
    'telephones': [
        { property: 'ram', title: 'RAM' },
        { property: 'stockage', title: 'Stockage' },
        { property: 'type_stockage', title: 'Type de stockage' },
        { property: 'processeur', title: 'Processeur' },
        { property: 'taille_ecran', title: 'Taille écran' },
        { property: 'etat', title: 'Etat' }
    ],
    'tablettes': [
        { property: 'ram', title: 'RAM' },
        { property: 'stockage', title: 'Stockage' },
        { property: 'type_stockage', title: 'Type de stockage' },
        { property: 'processeur', title: 'Processeur' },
        { property: 'taille_ecran', title: 'Taille écran' },
        { property: 'etat', title: 'Etat' }
    ],
    'casques-micros': [
        { property: 'audio', title: 'Audio' },
        { property: 'connectivite', title: 'Connectivité' },
        { property: 'connectique', title: 'Connectique' },
        { property: 'etat', title: 'Etat' }
    ],
    'claviers': [
        { property: 'clavier', title: 'Clavier' },
        { property: 'autonomie_batterie', title: 'Autonomie de la batterie' },
        { property: 'connectivite', title: 'Connectivité' },
        { property: 'connectique', title: 'Connectique' },
        { property: 'etat', title: 'Etat' }
    ],
    'souris': [
        { property: 'autonomie_batterie', title: 'Autonomie de la batterie' },
        { property: 'connectivite', title: 'Connectivité' },
        { property: 'connectique', title: 'Connectique' },
        { property: 'etat', title: 'Etat' }
    ],
    "adaptateurs": [
        { property: 'connectique', title: 'Connectique' },
        { property: 'alimentation', title: 'Alimentation' },
        { property: 'etat', title: 'Etat' }
    ],
    "imprimantes": [
        { property: 'type', title: 'Type' },
        { property: 'marque', title: 'Marque' },
        { property: 'modele', title: 'Modèle' },
        { property: 'etat', title: 'Etat' }
    ],
    "licences": [
        { property: 'nom_produit', title: 'Nom du produit' },
        { property: 'fournisseur', title: 'Fournisseur' },
        { property: 'type_licence', title: 'Type de licence' }
    ],
    "cables": [
        { property: 'marque', title: 'Marque' },
        { property: 'etat', title: 'Etat' }
    ],
    "Autres": [
        { property: 'marque', title: 'Marque' },
        { property: 'modele', title: 'Modèle' },
        { property: 'etat', title: 'Etat' }
    ]
};

export const typeEquipements = [
    { value: "ordinateurs", label: "Ordinateur" },
    { value: "ecrans", label: "Écran" },
    { value: "telephones", label: "Téléphone" },
    { value: "tablettes", label: "Tablette" },
    { value: "casques-micros", label: "Casques/Micros" },
    { value: "claviers", label: "Claviers" },
    { value: "souris", label: "Souris" },
    { value: "adaptateurs", label: "Adaptateurs" },
    { value: "imprimantes", label: "Imprimantes"},
    { value: "cables", label: "Câbles" },
    { value: "Autres", label: "Autre" },
];

export const filterMappingProduct = {
    'ordinateurs': {
        'price': 'prix_location',
        'Marques': 'marque',
        'Capacité de stockage': 'stockage',
        'Mémoire RAM': 'ram',
        // 'Type de processeur': 'processeur',
        'Poids': 'poids'
    },
    'ecrans': {
        'price': 'prix_location',
        'Marques': 'marque',
        'Taille écran': 'taille_ecran',
        'Résolution écran': 'resolution_ecran',
        'Poids': 'poids'
    },
    'telephones': {
        'price': 'prix_location',
        'Marques': 'marque',
        'Capacité de stockage': 'stockage',
        'Mémoire RAM': 'ram',
        'Poids': 'poids'
    },
    'tablettes': {
        'price': 'prix_location',
        'Marques': 'marque',
        'Capacité de stockage': 'stockage',
        'Mémoire RAM': 'ram',
        'Poids': 'poids'
    },
    'casques-micros': {
        'price': 'prix_location',
        'Marques': 'marque',
        'Audio': 'audio'
    },
    'claviers': {
        'price': 'prix_location',
        'Marques': 'marque'
    },
    'souris': {
        'price': 'prix_location',
        'Marques': 'marque'
    },
    "adaptateurs": {
        'price': 'prix_location',
        'Marques': 'marque'
    },
    "imprimantes": {
        'price': 'prix_location',
        'Marques': 'marque'
    },
    "licences": {
        'price': 'prix_location',
        'Fournisseur': 'fournisseur'
    },
    "cables": {
        'price': 'prix_location',
        'Marques': 'marque'
    },
};

export const genderMap = {
    'ordinateurs': 'm',
    'ecrans': 'm',
    'telephones': 'm',
    'tablettes': 'f',
    'casques-micros': 'm',
    'claviers': 'm',
    'souris': 'f',
    'adaptateurs': 'm',
    'imprimantes': 'f',
    'licences': 'f',
    'cables': 'm',
};

export const colors = [
    { title: 'Orange', hex: "#fc850a", val: "orange" },
    { title: 'Rouge', hex: "#ef5944", val: "red" },
    { title: 'Violet', hex: "#7070ff", val: "main" },
    { title: 'Indigo', hex: "#0bc0da", val: "indigo" },
    { title: 'Jaune', hex: "#fbb20b", val: "yellow" },
    { title: 'Vert', hex: "#0dd27a", val: "green" },
    { title: 'Rose', hex: "#f44d97", val: "pink" },
    { title: 'Noir', hex: "#000000", val: "black" },
    { title: 'Gris', hex: "#556987", val: "grey" },
];
